"use strict";
const APPROVAL_ACTIONS = Object.freeze({
  POI_NEW: "POI_NEW",
  POI_DELETE: "POI_DELETE",
  POI_UPDATE: "POI_UPDATE",
  POI_IMAGE_ADD: "POI_IMAGE_ADD",
  POI_IMAGE_DELETE: "POI_IMAGE_DELETE",
  POI_USER_ADD: "POI_USER_ADD",
  POI_USER_DELETE: "POI_USER_DELETE",
  POI_FOOTAGE_DELETE: "POI_FOOTAGE_DELETE",
  USER_NEW: "USER_NEW",
  USER_UPDATE: "USER_UPDATE",
  USER_DELETE: "USER_DELETE",
  USER_ADD_ROLE: "USER_ADD_ROLE",
  USER_REMOVE_ROLE: "USER_REMOVE_ROLE",
  ROLE_NEW: "ROLE_NEW",
  ROLE_UPDATE: "ROLE_UPDATE",
  ROLE_DELETE: "ROLE_DELETE",
  EDGE_DELETE: "EDGE_DELETE",
  EDGE_NEW: "EDGE_NEW"
});
const LOG_ACTIONS = Object.freeze({
  POI_CREATE: "CREATE POI",
  POI_CREATE_APPROVAL_ACTION: "CREATE POI APPROVAL ACTION",
  POI_DELETE: "DELETE POI",
  POI_DELETE_APPROVAL_ACTION: "DELETE POI APPROVAL ACTION",
  POI_IMAGE_ADD: "ADD IMAGE TO POI",
  POI_IMAGE_ADD_APPROVAL_ACTION: "ADD IMAGE TO POI APPROVAL ACTION",
  POI_IMAGE_DELETE: "DELETE IMAGE FROM POI",
  POI_IMAGE_DELETE_APPROVAL_ACTION: "DELETE IMAGE FROM POI APPROVAL ACTION",
  POI_USER_ADD: "POI_USER_ADD",
  POI_USER_ADD_APPROVAL_ACTION: "POI_USER_ADD_APPROVAL_ACTION",
  POI_USER_DELETE: "POI_USER_DELETE",
  POI_USER_DELETE_APPROVAL_ACTION: "POI_USER_DELETE_APPROVAL_ACTION",
  POI_FOOTAGE_DELETE: "DELETE FOOTAGE FROM POI",
  POI_FOOTAGE_DELETE_APPROVAL_ACTION:
    "DELETE FOOTAGE FROM POI  APPROVAL ACTION",
  IMAGE_CREATE: "CREATE IMAGE",
  EDGE_RECOGNIZED_POI: "RECOGNIZED POI AND UPLOAD FOOTAGE",
  APPROVAL_CREATE: "APPROVAL POI",
  APPROVAL_ITEM_REJECTED: "APPROVAL ITEM REJECTED",
  USER_CREATE: "CREATE USER",
  USER_CREATE_APPROVAL_ACTION: "CREATE USER APPROVAL ACTION",
  USER_UPDATE: "UPDATE USER",
  USER_UPDATE_APPROVAL_ACTION: "UPDATE USER APPROVAL ACTION",
  USER_DELETE: "DELETE USER",
  USER_DELETE_APPROVAL_ACTION: "DELETE USER APPROVAL ACTION",
  USER_ROLE_ADD: "ADD ROLE TO USER",
  USER_ROLE_ADD_APPROVAL_ACTION: "ADD ROLE TO USER APPROVAL ACTION",
  USER_ROLE_REMOVE: "REMOVE ROLE FROM USER",
  USER_ROLE_REMOVE_APPROVAL_ACTION: "REMOVE ROLE FROM USER APPROVAL ACTION",
  USER_AUTH: "USER LOGIN",
  ROLE_CREATE: "CREATE ROLE",
  ROLE_CREATE_APPROVAL_ACTION: "CREATE ROLE APPROVAL ACTION",
  ROLE_UPDATE: "UPDATE ROLE",
  ROLE_UPDATE_APPROVAL_ACTION: "UPDATE ROLE APPROVAL ACTION",
  ROLE_DELETE: "DELETE ROLE",
  ROLE_DELETE_APPROVAL_ACTION: "DELETE ROLE APPROVAL ACTION",
  EDGE_CREATE: "CREATE EDGE",
  EDGE_CREATE_APPROVAL_ACTION: "CREATE EDGE APPROVAL ACTION",
  EDGE_DELETE: "DELETE EDGE",
  EDGE_DELETE_APPROVAL_ACTION: "DELETE EDGE APPROVAL ACTION",
  EDGE_CERTIFICATES_DOWNLOADED: "EDGE CERTIFICATES DOWNLOADED"
});

const RESOURCE_TYPES = Object.freeze({
  POI: "POI",
  USER: "USER",
  IMAGE: "IMAGE",
  EDGE: "EDGE"
});

const AWS_RESOURCE = Object.freeze({
  //AWS IOT
  THING_TYPENAME: "WYF_Edge_Node",
  THING_GROUPARN: "arn:aws:iot:eu-central-1:693188760610:thinggroup/wyf_edges",
  THING_GROUPNAME: "wyf_edges",
  THING_POLICYNAME: "wyf_edges_permitall",
  THING_IOT_ENDPOINT: "a95auszam8l8d.iot.eu-central-1.amazonaws.com",
  //AWS Batch
  BATCH_JOBDEFINITION: "BATCH-JOBDEFI-Fog-Computing",
  BATCH_JOBNAME: "ModelTraining",
  BATCH_JOBQUEUE: "BATCH-QUEUE-Fog-Computing"
});

const COMPONENT_TYPES = Object.freeze({
  EDGE: "EDGE"
});

const LOG_LEVEL = Object.freeze({
  DEBUG: "DEBUG",
  VERBOSE: "VERBOSE",
  IMPORTANT: "IMPORTANT",
  WARNING: "WARNING",
  ERROR: "ERROR",
  CRITICAL_ERROR: "CRITICAL_ERROR"
});

const LOG_SYSTEM_ACTIONS = Object.freeze({
  EDGE_RECOGNIZED_POI: "RECOGNIZED POI AND UPLOAD FOOTAGE"
});

module.exports = {
  LOG_ACTIONS: LOG_ACTIONS,
  APPROVAL_ACTIONS: APPROVAL_ACTIONS,
  RESOURCE_TYPES: RESOURCE_TYPES,
  AWS_RESOURCE: AWS_RESOURCE,
  COMPONENT_TYPES: COMPONENT_TYPES,
  LOG_LEVEL: LOG_LEVEL,
  LOG_SYSTEM_ACTIONS: LOG_SYSTEM_ACTIONS
};
