language: node_js
node_js:
 - "v10.6.0"

cache:
  yarn: true
  directories:
    - frontend/node_modules

install:
  - ( cd frontend && yarn install --non-interactive )
  - yarn install --non-interactive
  - yarn global add serverless@1.27.3

script:
  - .travis/travis-script.sh

deploy:
  - provider: script
    skip_cleanup: true
    script: bash .travis/travis-deploy.sh
    on:
      all_branches: true

# deploy:
#   on:
#     branch: master
#   provider: s3
#   access_key_id: $AWS_ACCESS_KEY
#   secret_access_key: $AWS_SECRET_ACCESS_KEY
#   bucket: watchyourfac.es
#   local_dir: dist
#   skip_cleanup: true
#   acl: public_read
#   region: $AWS_DEFAULT_REGION
